# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161104_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(db_index=True, default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Artist'),
        ),
    ]
